spring:
   boot:
      admin:
         client:
            url: 'http://localhost:9090'

server:
   port: 9090
            
eureka:
   instance:
      leaseRenewalIntervalInSeconds: 10
      health-check-url-path: /actuator/health
      metadata-map:
         # needed to trigger info and endpoint update after restart
         startup: ${random.int}
   client:
      registryFetchIntervalSeconds: 5
      serviceUrl:
         defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
   endpoints:
      web:
         exposure:
            include: '*'

# Emit logs to file with standard spring log patterns.
# This is so SBA can consume and display logs
logging:
   path: 'logs/'
   file: '${logging.path}/application.log'
   pattern.file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'